from telegram import Update
from telegram.ext import ContextTypes

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 Welcome to *TakoNautBot*!\n\n"
        "💱 *Currency Conversion:*\n"
        "`100 USD to IDR`\n"
        "`2500 JPY to EUR`\n\n"
        "📏 *Unit Conversion:*\n"
        "`170 cm to ft`\n"
        "`25 c to f`\n\n"
        "🈳 *Text Translation:*\n"
        "Reply to any message:\n"
        "`/tl en` (Translate to English)\n\n"
        "🖼️ *Image Translation:*\n"
        "Reply to an image:\n"
        "`/tlpic <image_lang> <target_lang>`\n"
        "Example: `/tlpic ja en`\n\n"
        "🔔 *Reminder:*\n"
        "Set one-time reminder:\n"
        "`/remind <time> <message>`\n"
        "Example: `/remind 10m report`\n\n"
        "Set daily reminder:\n"
        "`/remind daily <message>`\n"
        "Example: `/remind daily report`\n\n"
        "Set weekly reminder:\n"
        "`/remind weekly <weekday> <message>`\n"
        "Example: `/remind weekly Monday report`\n\n"
        "Set monthly reminder:\n"
        "`/remind monthly <day> <message>`\n"
        "Example: `/remind monthly 25 payday`\n\n"
        "Set yearly reminder:\n"
        "`/remind yearly <day> <month> <message>`\n"
        "Example: `/remind yearly 11 Jan Happy Birthday`\n\n"
        "List reminders:\n"
        "`/reminder_list`\n\n"
        "Delete reminder:\n"
        "`/reminder_delete <id>`\n"
        "Example: `/reminder_delete 123`\n\n"
        "Set your timezone:\n"
        "`/timezone <tz>`\n"
        "Example: `/timezone Asia/Tokyo`\n\n"
        "Use `/help` for details.\n",
        parse_mode="Markdown"
    )