name: Deploy TakoNautBot

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for version/metadata only)
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server: pull, install deps, restart service
        env:
          WORKDIR: ${{ secrets.WORKDIR || '/srv/TakoNautBot' }}
          PYTHON_BIN: ${{ secrets.PYTHON_BIN || '/srv/TakoNautBot/.venv/bin/python' }}
          SERVICE: ${{ secrets.SERVICE_NAME }}
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" bash -lc "
            set -euo pipefail
            cd \"${WORKDIR}\"

            echo '▶ Fetch & reset to origin/main'
            git fetch --all
            git reset --hard origin/main

            echo '▶ Ensure venv & dependencies'
            if [ ! -x .venv/bin/python ]; then
              python3 -m venv .venv
            fi
            . .venv/bin/activate
            python -V
            pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            echo '▶ Restart systemd service'
            sudo systemctl restart \"${SERVICE}.service\"
            sudo systemctl --no-pager --full status \"${SERVICE}.service\" | sed -n '1,40p'
          "
